### ISSUE TITLE
Audio device with 6 channels

### ISSUE THREAD

**Issue by tW4r** [5T33Z0/AppleALC-Guides#1]
Thank you for the informative tutorial.

Do you happen to know if there is a way to setup the layout/platform in such a way that macOS would see an audio device with 6 output channels (5.1 audio) rather than 2 output channels (Left/Right Stereo)

**Comment by 5T33Z0** [comment]
It works the same, just more outputs you have to route. Have a look at Desktop Layouts which support 5.1 audio mappings for reference. Layout 17 of ALC1220 for example:

![Bildschirmfoto 2022-11-20 um 15 19 39](https://user-images.githubusercontent.com/76865553/202907560-528cacf0-f5b8-4afe-9509-b72b56edbb15.png)
