### ISSUE TITLE
Clarifications on Tracing Possible Paths section

### ISSUE THREAD

**Issue by joaobertacchi** [5T33Z0/AppleALC-Guides#4]
@5T33Z0, in [Tracing Possible Paths section](https://github.com/5T33Z0/AppleALC-Guides/tree/main/AppleALC_Layout-ID#tracing-possible-paths), you say that "After a many, many trials, I settled with the following routing". Here I managed to create a list with all possible paths for my platform. However its unclear how to reduce that to a list of "valid" paths.
Could you, please, explain what tries you did? How do you check if they are valid or not?

I'm trying to create a new layout-id for ALC897. Existing ones does not work (I don't see my onboarding audio card as an output). I suppose there are 3 steps: 1) seen onboarding card as an audio output; 2) making sound play from it; 3) adding extra audio jacks to may config. Does it make sense? If so, focusing only on speaker/line out Pin Complex should be enough to achieve (1) and (2)?

Thanks!

**Comment by 5T33Z0** [comment]
Well, you just have to try a routing, compile the kext, test it and try a different one if it doesn't work until no more options are available.  An easier way would be to use alc-verb to test a routing. But I don't know how this works.

Unless the on-board audio is recognized by the system, creating a new AppleALC Layout doesn't make sense.

Good Luck.
