### ISSUE TITLE
Help Me for Layout X1 Tablet 3° Gen

### ISSUE THREAD

**Issue by Baio1977** [5T33Z0/AppleALC-Guides#5]
[Dump Linux ALC 295 X1 Tablet.zip](https://github.com/5T33Z0/AppleALC-Guides/files/11137222/Dump.Linux.ALC.295.X1.Tablet.zip)

Reposity:
https://github.com/Baio1977/Lenovo-ThinkPad-X1-Tablet-Gen3-Kabylake-r

I extracted files, for me it's a bit difficult.
I hope you can help me improve the audio setup.

**Comment by Sauvio** [comment]
[ALC236.zip](https://github.com/5T33Z0/AppleALC-Guides/files/11167310/ALC236.zip)

Thank you so much for writing this guide and this is helpful.
I try to learn how to customize the layout and platform, I want to automatically switch the sound output while being able to manually select the sound output. That is to say, when I plug in the 3.5mm interface microphone and headphone jack, the sound is output to the headphone, but I can still select the speaker to output in the sound control panel. At this point, I tried to mix manual configuration and automatic configuration, but it didn't work. Is it possible to do this?

**Comment by 5T33Z0** [comment]
Don't ask me to fix your Layouts. I don't have the time nor the patience-
