### ISSUE TITLE
Suggestion for using Microsoft High Definition Audio Utility

### ISSUE THREAD

**Issue by dsanke** [5T33Z0/AppleALC-Guides#7]
From this thread: https://bbs.pcbeta.com/viewthread-1847616-1-1.html and this video: https://www.bilibili.com/video/av50809670
![231322d87tfxeb0totx99b](https://github.com/5T33Z0/AppleALC-Guides/assets/2108751/cc9cc341-2732-450f-b6e0-7564f5835968)
![230402le55m1o0c2c61co2](https://github.com/5T33Z0/AppleALC-Guides/assets/2108751/700e4a22-18af-478e-af98-229d49769270)

**Comment by 5T33Z0** [comment]
Interesting. Seems like a WIndows app for creating the layput. This could make things a lot easier

**Comment by Core-i99** [comment]
I've downloaded a copy of it from archive.org.
What does this provide that codec graph doesn't?
It is good that we don't need a codec dump from oc/clover/linux because it can import it from the local machine

**Comment by 5T33Z0** [comment]
> I've downloaded a copy of it from archive.org. What does this provide that codec graph doesn't? It is good that we don't need a codec dump from oc/clover/linux because it can import it from the local machine

Did you read my messages on discord regarding your pc version of Codec Graph I sent you about 2 months ago?

**Comment by dsanke** [comment]
[HDAU_TOOL.zip](https://github.com/5T33Z0/AppleALC-Guides/files/11718996/HDAU_TOOL.zip)
Uninstall audio driver provided by Realtek, just use the Microsoft Windows provided basic High Definition Audio driver, then use this, it should show graph.

**Comment by 5T33Z0** [comment]
Thanks. I will check it out later.

**Comment by ugoobi007** [comment]
Hi, @5T33Z0, would you mind helping me with my audio> It is a ALC3246(256) for a dell OptiPlex 5260 AIO. It has a built in speaker, a side headphone jack, rear audio out jack and a built-in mic. I have tried all the LayoutIDs. Only 67 shows both the side headphone and rear audio out, but the internal mic does not work. Also the other layoutid, like 21 that i eventually settled for, only the internal speaker, headphone jack and build-in Mic work. The rear audio out does not work. Would appreciate if you could help create a fully working audio. Thanks
![Dell Optiplex 5260 AIO Side View](https://github.com/5T33Z0/AppleALC-Guides/assets/75176210/ed8e7e27-a588-4ed0-a477-547b6ecef1dc)
![Dell Optiplex 5260 AIO Rear View](https://github.com/5T33Z0/AppleALC-Guides/assets/75176210/cb01da97-f994-48ba-89e3-2fefd526351d). Thanks
