### ISSUE TITLE
How to edit related files if you only want the built-in speaker to sound

### ISSUE THREAD

**Issue by aTan20170106** [5T33Z0/AppleALC-Guides#8]
Hello, may I ask a question about how to edit the Platforms.XML, layout.xml, and info.plist files to make the built-in speaker sound. Especially when dealing with data under PathMap child nodes in the fixed format of Platforms.XML. For example, the ALC287 of the Yoga Duet IML 2020 laptop currently cannot drive the built-in speaker using Alcid: 21. Can we solve this problem by first resolving the built-in speaker and then processing other nodes.

**Comment by 5T33Z0** [comment]
I suggest you use Layout 21 as a base and modify the files as explained in-depth in [the guide](https://github.com/5T33Z0/AppleALC-Guides/tree/main/AppleALC_Layout-ID).

**Comment by aTan20170106** [comment]
I have read the guide before and have identified the speaker nodes, headphones, and microphone nodes. Modified Platforms in ALC287 XML, layout.xml, info.plist, PinConfigs.kext, but have not been successful. So use the exclusion method to determine whether each valid node is valid.

Platforms The child nodes under XML, PathMaps ->PathMap, have two main categories of input and output, but currently only the built-in speakers in the output are needed. I don't need anything else, I don't know how to handle it at this point.
Obtained code file
[codec#0.txt](https://github.com/5T33Z0/AppleALC-Guides/files/13557580/codec.0.txt)
