### ISSUE TITLE
Suggested addition

### ISSUE THREAD

**Issue by big-mak** [5T33Z0/AppleALC-Guides#9]
The guide should mention that you should check first whether audio works under linux before proceeding with dumping the codec etc.. Users can check [here](linux-hardware.org) whether others have been able to get audio working under linux on their device (I recommend running a probe to ensure you get the exact right model). I don't imagine it's possible to get AppleALC working if you can't get linux working first.

**Comment by 5T33Z0** [comment]
Thanks. I've adde your suggestion  to the guide: https://github.com/5T33Z0/AppleALC-Guides/tree/main/AppleALC_Layout-ID#obtaining-an-audio-codec-dump-in-linux
